#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install jupyter_firefly_extensions
jupyter serverextension enable --py jupyter_firefly_extensions
